#############################################################################
# Makefile for building: ../out/tranrem
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?? ??? 16 13:53:03 2011
# Project:  tranrem.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile tranrem.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude -I../tmp
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ../tmp/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		transmrpcsession.cpp \
		lib/json_reader.cpp \
		lib/json_value.cpp \
		lib/json_writer.cpp \
		torrent.cpp ../tmp/moc_mainwindow.cpp \
		../tmp/moc_transmrpcsession.cpp
OBJECTS       = ../tmp/main.o \
		../tmp/mainwindow.o \
		../tmp/transmrpcsession.o \
		../tmp/json_reader.o \
		../tmp/json_value.o \
		../tmp/json_writer.o \
		../tmp/torrent.o \
		../tmp/moc_mainwindow.o \
		../tmp/moc_transmrpcsession.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		tranrem.pro
QMAKE_TARGET  = tranrem
DESTDIR       = ../out/
TARGET        = ../out/tranrem

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ../out/ || $(MKDIR) ../out/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tranrem.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile tranrem.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile tranrem.pro

dist: 
	@$(CHK_DIR_EXISTS) ../tmp/tranrem1.0.0 || $(MKDIR) ../tmp/tranrem1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../tmp/tranrem1.0.0/ && $(COPY_FILE) --parents mainwindow.h transmrpcsession.h include/json/autolink.h include/json/config.h include/json/features.h include/json/forwards.h include/json/json.h include/json/reader.h include/json/value.h include/json/writer.h torrent.h ../tmp/tranrem1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp transmrpcsession.cpp lib/json_reader.cpp lib/json_value.cpp lib/json_writer.cpp torrent.cpp ../tmp/tranrem1.0.0/ && (cd `dirname ../tmp/tranrem1.0.0` && $(TAR) tranrem1.0.0.tar tranrem1.0.0 && $(COMPRESS) tranrem1.0.0.tar) && $(MOVE) `dirname ../tmp/tranrem1.0.0`/tranrem1.0.0.tar.gz . && $(DEL_FILE) -r ../tmp/tranrem1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: ../tmp/moc_mainwindow.cpp ../tmp/moc_transmrpcsession.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../tmp/moc_mainwindow.cpp ../tmp/moc_transmrpcsession.cpp
../tmp/moc_mainwindow.cpp: transmrpcsession.h \
		torrent.h \
		errorcodes.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o ../tmp/moc_mainwindow.cpp

../tmp/moc_transmrpcsession.cpp: torrent.h \
		errorcodes.h \
		transmrpcsession.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) transmrpcsession.h -o ../tmp/moc_transmrpcsession.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

../tmp/main.o: main.cpp mainwindow.h \
		transmrpcsession.h \
		torrent.h \
		errorcodes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/main.o main.cpp

../tmp/mainwindow.o: mainwindow.cpp mainwindow.h \
		transmrpcsession.h \
		torrent.h \
		errorcodes.h \
		tags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/mainwindow.o mainwindow.cpp

../tmp/transmrpcsession.o: transmrpcsession.cpp transmrpcsession.h \
		torrent.h \
		errorcodes.h \
		tags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/transmrpcsession.o transmrpcsession.cpp

../tmp/json_reader.o: lib/json_reader.cpp lib/json_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/json_reader.o lib/json_reader.cpp

../tmp/json_value.o: lib/json_value.cpp lib/json_batchallocator.h \
		lib/json_internalarray.inl \
		lib/json_internalmap.inl \
		lib/json_valueiterator.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/json_value.o lib/json_value.cpp

../tmp/json_writer.o: lib/json_writer.cpp lib/json_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/json_writer.o lib/json_writer.cpp

../tmp/torrent.o: torrent.cpp torrent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/torrent.o torrent.cpp

../tmp/moc_mainwindow.o: ../tmp/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/moc_mainwindow.o ../tmp/moc_mainwindow.cpp

../tmp/moc_transmrpcsession.o: ../tmp/moc_transmrpcsession.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmp/moc_transmrpcsession.o ../tmp/moc_transmrpcsession.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

